"""add chunk metadata columns, parent_chunk_id, jsonb

Revision ID: a04d5680dde2
Revises: 
Create Date: 2026-08-28 11:20:27.196090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a04d5680dde2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # article_title/source_url добавляем NULLABLE и бэкфиллим из articles —
    # в таблице уже есть данные (GTS/Human/AC), автоген хотел сразу NOT NULL
    # без дефолта, что упало бы на существующих строках.
    op.add_column('article_chunks', sa.Column('article_title', sa.String(length=255), nullable=True))
    op.add_column('article_chunks', sa.Column('source_url', sa.String(), nullable=True))
    op.add_column('article_chunks', sa.Column('section_path', sa.String(length=500), nullable=True))
    op.add_column('article_chunks', sa.Column('chunk_type', sa.String(length=20), server_default='text', nullable=False))
    op.add_column('article_chunks', sa.Column('parent_chunk_id', sa.Integer(), nullable=True))

    op.execute("""
        UPDATE article_chunks AS ac
        SET article_title = a.title,
            source_url = a.url
        FROM articles AS a
        WHERE ac.article_id = a.id
    """)

    op.alter_column('article_chunks', 'article_title', nullable=False)
    op.alter_column('article_chunks', 'source_url', nullable=False)
    op.alter_column('article_chunks', 'metadata_obj',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_foreign_key(None, 'article_chunks', 'article_chunks', ['parent_chunk_id'], ['id'], ondelete='SET NULL')
    op.alter_column('articles', 'metadata_obj',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'metadata_obj',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_constraint(None, 'article_chunks', type_='foreignkey')
    op.alter_column('article_chunks', 'metadata_obj',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_column('article_chunks', 'parent_chunk_id')
    op.drop_column('article_chunks', 'chunk_type')
    op.drop_column('article_chunks', 'section_path')
    op.drop_column('article_chunks', 'source_url')
    op.drop_column('article_chunks', 'article_title')
    # ### end Alembic commands ###
